---
title: Avani Tavargeri
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  project-categories:
    title: Project Categories
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: projects
  values:
    layout: project
    subtitle: 
    thumbnail image: 
    project category: 
    description:
      icon: 
      text: 
    key focus areas:
    - 
    top image: 
    section two:
      title: 
      text: 
    gallery:
    - image: 
      text: 
description: Avani Tavargeri, a Product & User Experience designer portfolio website.
email: avani.tavargeri@gmail.com
permalink: pretty
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
plugins:
- jekyll-seo-tag
- jekyll-sitemap
behance: https://www.behance.net/avani-tavargeri
linkedin: https://www.linkedin.com/in/avanitavargeri
instagram: https://www.instagram.com/avanitavargeri
url: https://www.avanidesign.works
